# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.password import Password  # noqa: F401,E501
from swagger_server.models.user_name import UserName  # noqa: F401,E501
from swagger_server import util


class LoginUserByUserName(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, password: str=None, username: str=None):  # noqa: E501
        """LoginUserByUserName - a model defined in Swagger

        :param password: The password of this LoginUserByUserName.  # noqa: E501
        :type password: str
        :param username: The username of this LoginUserByUserName.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'password': str,
            'username': str
        }

        self.attribute_map = {
            'password': 'password',
            'username': 'username'
        }
        self._password = password
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'LoginUserByUserName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginUserByUserName of this LoginUserByUserName.  # noqa: E501
        :rtype: LoginUserByUserName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def password(self) -> str:
        """Gets the password of this LoginUserByUserName.

        specified account password  # noqa: E501

        :return: The password of this LoginUserByUserName.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginUserByUserName.

        specified account password  # noqa: E501

        :param password: The password of this LoginUserByUserName.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def username(self) -> str:
        """Gets the username of this LoginUserByUserName.

        user unique public identifcation name handle  # noqa: E501

        :return: The username of this LoginUserByUserName.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this LoginUserByUserName.

        user unique public identifcation name handle  # noqa: E501

        :param username: The username of this LoginUserByUserName.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username
