# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.email import Email  # noqa: F401,E501
from swagger_server.models.password import Password  # noqa: F401,E501
from swagger_server import util


class LoginUserByEmail(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, password: str=None, email: str=None):  # noqa: E501
        """LoginUserByEmail - a model defined in Swagger

        :param password: The password of this LoginUserByEmail.  # noqa: E501
        :type password: str
        :param email: The email of this LoginUserByEmail.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'password': str,
            'email': str
        }

        self.attribute_map = {
            'password': 'password',
            'email': 'email'
        }
        self._password = password
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'LoginUserByEmail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginUserByEmail of this LoginUserByEmail.  # noqa: E501
        :rtype: LoginUserByEmail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def password(self) -> str:
        """Gets the password of this LoginUserByEmail.

        specified account password  # noqa: E501

        :return: The password of this LoginUserByEmail.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginUserByEmail.

        specified account password  # noqa: E501

        :param password: The password of this LoginUserByEmail.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self) -> str:
        """Gets the email of this LoginUserByEmail.

        email of the user  # noqa: E501

        :return: The email of this LoginUserByEmail.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this LoginUserByEmail.

        email of the user  # noqa: E501

        :param email: The email of this LoginUserByEmail.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email
